version: "3.9"

services:
  # database service
  postgresql_db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_DATABASE=basic_dev
      - POSTGRES_USER=basic_dev
      - POSTGRES_PASSWORD=basic_dev
    ports:
      - "5432:5432" # map container port 5432 to 5432 on host
    volumes:
      - postgres_data:/data/db

  # admin tool for postgresql db
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5433:80" # map container port 80 to 5433 on host
    volumes:
      - pgadmin:/root/.pgadmin

  # basic .NET 6 minimal
  basicapi:
    container_name: api_container
    build:
      context: ./basicapi
      dockerfile: Dockerfile
    depends_on:
      - postgresql_db
    ports:
      - "3000:80" # map container port 80 to 3000 on host

volumes:
  postgres_data:
  pgadmin: